apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fc3qou6lz-nodejs
  janus-idp.io/tekton: fc3qou6lz-nodejs
  backstage.io/kubernetes-id: fc3qou6lz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fc3qou6lz-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
