apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fc3qou6lz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fc3qou6lz-nodejs 
  name: fc3qou6lz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fc3qou6lz-nodejs 
